# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "momamene"
description: > #this this means to ignore newlines until "email:"
   Deep Learning, Web Design, Software Engineering

email: momamene@gmail.com
#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/header.png"

name: "momamene"
author: momamene
author_image: "/assets/images/author.png"

paginate: 5

url: "http://blog.umay.be" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@momamil'

#fill in disqus shortname to use disqus
disqus: momamene

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/momamil
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/momamene
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/momamene
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
